name: Run the code di Raspberry Pi

on:
  push:
    branches: [main]  # Jalankan saat kamu push ke branch 'main'

jobs:
  run_logger:
    runs-on: [self-hosted, raspi5]  # Sesuai label di runner kamu

    steps:
      - uses: actions/checkout@v3  # Tarik isi repo

      - name: Matikan proses logger_main.py (jika ada)
        run: |
          pkill -f logger_main.py || true

      - name: Jalankan logger_main.py
        run: |
          nohup python3 logger_main.py > logger.log 2>&1 &
