name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: raspi5

    steps:
      - uses: actions/checkout@v3

      - name: Jalankan kode Python
        run: python logger_main.py

      - name: Restart service (contoh)
        run: python logger_main.py
