name: Run logger_main.py di Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  run-logger:
    runs-on: [self-hosted, raspi5]
    steps:
      - uses: actions/checkout@v3
      - name: Jalankan logger_main.py
        run: |
          pkill -f logger_main.py || true
          nohup python3 logger_main.py > logger.log 2>&1 &
